name: CI 

on:
  push:
    branches:
      - main
    paths:
      - "hangman-api/**"
  pull_request:
    branches:
      - main
    paths:
      - "hangman-api/**"

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node version: [14.x, 15.x, 16.x]

    steps:
      - uses: actions/checkout@v3
      - name: inspect
        run: |
          ls -al 
          echo Hola 
          whoami
          pwd
          node -v
          docker version
          docker compose version
      - name: build and test
        working-directory: ./hangman-api
        run: |
          npm ci
          npm run build --if-present 
          ls ./dist
          npm test
